### ISSUE TITLE
Multiple paths uni-dimensional, Gradient Estimation in TensorFlow (with likelihood ratio)

### ISSUE THREAD

**Issue by dionman** [thiagopbueno/gradient-estimators-in-stochastic-computation-graphs#1]
Thanks for sharing this useful piece of code!
If I interpret correctly the formulae in the paper,     

> `grad_log_theta, = tf.gradients(xs=theta, ys=(f * log_prob), stop_gradients=[y, z])`

should be computing only the gradient wrt theta of log_prob and then multiplying with  f:
is the implementation with this command correct?
It seems to me that it computes the gradient of the entire expression f*log_prob - or am I missing something?

**Comment by thiagopbueno** [comment]
Hi @dionman,

Indeed I am computing the gradient of the entire expression. But since I'm stopping the gradients on y and z, then f is treated as a constant wrt the parameters theta, and consequently grad_log_theta is the correct score function estimator of the stochastic computation graph.

I could have stopped the gradients on f itself, but I wanted to emphasize that one could block the multiple paths directly.

Is it clearer?

**Comment by dionman** [comment]
yes, thanks for the explanation
